# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'skqt.ui'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_SkedYes(object):
    def setupUi(self, SkedYes):
        SkedYes.setObjectName(_fromUtf8("SkedYes"))
        SkedYes.resize(1280, 1024)
        SkedYes.setFocusPolicy(QtCore.Qt.ClickFocus)
        SkedYes.setAutoFillBackground(True)
        SkedYes.setStyleSheet(_fromUtf8(""))
        self.header = QtGui.QLabel(SkedYes)
        self.header.setGeometry(QtCore.QRect(40, 40, 431, 71))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Black"))
        font.setPointSize(36)
        self.header.setFont(font)
        self.header.setTextFormat(QtCore.Qt.AutoText)
        self.header.setObjectName(_fromUtf8("header"))
        self.telnetConnection = QtGui.QLabel(SkedYes)
        self.telnetConnection.setGeometry(QtCore.QRect(50, 110, 360, 40))
        self.telnetConnection.setObjectName(_fromUtf8("telnetConnection"))
        self.stbSwVer = QtGui.QLabel(SkedYes)
        self.stbSwVer.setGeometry(QtCore.QRect(840, 730, 120, 40))
        self.stbSwVer.setObjectName(_fromUtf8("stbSwVer"))
        self.progressBar = QtGui.QProgressBar(SkedYes)
        self.progressBar.setGeometry(QtCore.QRect(40, 910, 740, 24))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.telnetEditorOuput = QtGui.QTextEdit(SkedYes)
        self.telnetEditorOuput.setGeometry(QtCore.QRect(40, 740, 740, 160))
        self.telnetEditorOuput.setObjectName(_fromUtf8("telnetEditorOuput"))
        self.stbEth0Mac = QtGui.QLabel(SkedYes)
        self.stbEth0Mac.setGeometry(QtCore.QRect(840, 770, 120, 40))
        self.stbEth0Mac.setObjectName(_fromUtf8("stbEth0Mac"))
        self.stbWiFiMac = QtGui.QLabel(SkedYes)
        self.stbWiFiMac.setGeometry(QtCore.QRect(840, 810, 120, 40))
        self.stbWiFiMac.setObjectName(_fromUtf8("stbWiFiMac"))
        self.modelInfo = QtGui.QLabel(SkedYes)
        self.modelInfo.setGeometry(QtCore.QRect(840, 850, 120, 40))
        self.modelInfo.setObjectName(_fromUtf8("modelInfo"))
        self.textStbSwVersion = QtGui.QTextEdit(SkedYes)
        self.textStbSwVersion.setGeometry(QtCore.QRect(960, 730, 260, 36))
        self.textStbSwVersion.setReadOnly(True)
        self.textStbSwVersion.setObjectName(_fromUtf8("textStbSwVersion"))
        self.textStbEth0Mac = QtGui.QTextEdit(SkedYes)
        self.textStbEth0Mac.setGeometry(QtCore.QRect(960, 770, 260, 36))
        self.textStbEth0Mac.setReadOnly(True)
        self.textStbEth0Mac.setObjectName(_fromUtf8("textStbEth0Mac"))
        self.textStbModel = QtGui.QTextEdit(SkedYes)
        self.textStbModel.setGeometry(QtCore.QRect(960, 850, 260, 36))
        self.textStbModel.setReadOnly(True)
        self.textStbModel.setAcceptRichText(True)
        self.textStbModel.setTextInteractionFlags(QtCore.Qt.TextSelectableByMouse)
        self.textStbModel.setObjectName(_fromUtf8("textStbModel"))
        self.textStbWifiMac = QtGui.QTextEdit(SkedYes)
        self.textStbWifiMac.setGeometry(QtCore.QRect(960, 810, 260, 36))
        self.textStbWifiMac.setReadOnly(True)
        self.textStbWifiMac.setObjectName(_fromUtf8("textStbWifiMac"))
        self.textStbHddSn = QtGui.QTextEdit(SkedYes)
        self.textStbHddSn.setGeometry(QtCore.QRect(960, 890, 260, 36))
        self.textStbHddSn.setReadOnly(True)
        self.textStbHddSn.setObjectName(_fromUtf8("textStbHddSn"))
        self.hddSn = QtGui.QLabel(SkedYes)
        self.hddSn.setGeometry(QtCore.QRect(840, 890, 120, 40))
        self.hddSn.setObjectName(_fromUtf8("hddSn"))
        self.dateAndTime = QtGui.QLabel(SkedYes)
        self.dateAndTime.setGeometry(QtCore.QRect(740, 10, 260, 24))
        self.dateAndTime.setText(_fromUtf8(""))
        self.dateAndTime.setObjectName(_fromUtf8("dateAndTime"))
        self.connectToStbButton = QtGui.QPushButton(SkedYes)
        self.connectToStbButton.setGeometry(QtCore.QRect(920, 80, 140, 50))
        self.connectToStbButton.setObjectName(_fromUtf8("connectToStbButton"))
        self.exitButton = QtGui.QPushButton(SkedYes)
        self.exitButton.setGeometry(QtCore.QRect(920, 200, 140, 50))
        self.exitButton.setObjectName(_fromUtf8("exitButton"))
        self.labelTunerTest = QtGui.QLabel(SkedYes)
        self.labelTunerTest.setGeometry(QtCore.QRect(50, 170, 160, 28))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 213, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(63, 191, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 113, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 212, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 213, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(63, 191, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 113, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 212, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 213, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(63, 191, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 113, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.labelTunerTest.setPalette(palette)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelTunerTest.setFont(font)
        self.labelTunerTest.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.labelTunerTest.setStyleSheet(_fromUtf8(""))
        self.labelTunerTest.setFrameShape(QtGui.QFrame.WinPanel)
        self.labelTunerTest.setIndent(-1)
        self.labelTunerTest.setObjectName(_fromUtf8("labelTunerTest"))
        self.labelHddTest = QtGui.QLabel(SkedYes)
        self.labelHddTest.setGeometry(QtCore.QRect(50, 210, 160, 28))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelHddTest.setFont(font)
        self.labelHddTest.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.labelHddTest.setStyleSheet(_fromUtf8(""))
        self.labelHddTest.setFrameShape(QtGui.QFrame.WinPanel)
        self.labelHddTest.setIndent(-1)
        self.labelHddTest.setObjectName(_fromUtf8("labelHddTest"))
        self.labelUsbTest = QtGui.QLabel(SkedYes)
        self.labelUsbTest.setGeometry(QtCore.QRect(50, 250, 160, 28))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelUsbTest.setFont(font)
        self.labelUsbTest.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.labelUsbTest.setFrameShape(QtGui.QFrame.WinPanel)
        self.labelUsbTest.setIndent(-1)
        self.labelUsbTest.setObjectName(_fromUtf8("labelUsbTest"))
        self.labelSmartcardTest = QtGui.QLabel(SkedYes)
        self.labelSmartcardTest.setGeometry(QtCore.QRect(50, 290, 160, 28))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelSmartcardTest.setFont(font)
        self.labelSmartcardTest.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.labelSmartcardTest.setFrameShape(QtGui.QFrame.WinPanel)
        self.labelSmartcardTest.setIndent(-1)
        self.labelSmartcardTest.setObjectName(_fromUtf8("labelSmartcardTest"))
        self.tunerTestProgressBar = QtGui.QProgressBar(SkedYes)
        self.tunerTestProgressBar.setGeometry(QtCore.QRect(230, 170, 120, 28))
        self.tunerTestProgressBar.setProperty("value", 5)
        self.tunerTestProgressBar.setObjectName(_fromUtf8("tunerTestProgressBar"))
        self.hddTestProgressBar = QtGui.QProgressBar(SkedYes)
        self.hddTestProgressBar.setGeometry(QtCore.QRect(230, 210, 120, 28))
        self.hddTestProgressBar.setProperty("value", 5)
        self.hddTestProgressBar.setObjectName(_fromUtf8("hddTestProgressBar"))
        self.usbTestProgressBar = QtGui.QProgressBar(SkedYes)
        self.usbTestProgressBar.setGeometry(QtCore.QRect(230, 250, 120, 28))
        self.usbTestProgressBar.setProperty("value", 5)
        self.usbTestProgressBar.setObjectName(_fromUtf8("usbTestProgressBar"))
        self.smartcardTestProgressbar = QtGui.QProgressBar(SkedYes)
        self.smartcardTestProgressbar.setGeometry(QtCore.QRect(230, 290, 120, 28))
        self.smartcardTestProgressbar.setProperty("value", 5)
        self.smartcardTestProgressbar.setObjectName(_fromUtf8("smartcardTestProgressbar"))
        self.tunerResult = QtGui.QLabel(SkedYes)
        self.tunerResult.setGeometry(QtCore.QRect(360, 170, 66, 28))
        self.tunerResult.setMouseTracking(False)
        self.tunerResult.setAutoFillBackground(True)
        self.tunerResult.setInputMethodHints(QtCore.Qt.ImhPreferUppercase)
        self.tunerResult.setFrameShape(QtGui.QFrame.NoFrame)
        self.tunerResult.setFrameShadow(QtGui.QFrame.Sunken)
        self.tunerResult.setAlignment(QtCore.Qt.AlignCenter)
        self.tunerResult.setObjectName(_fromUtf8("tunerResult"))
        self.hddResult = QtGui.QLabel(SkedYes)
        self.hddResult.setGeometry(QtCore.QRect(360, 210, 66, 28))
        self.hddResult.setMouseTracking(False)
        self.hddResult.setAutoFillBackground(True)
        self.hddResult.setInputMethodHints(QtCore.Qt.ImhPreferUppercase)
        self.hddResult.setFrameShape(QtGui.QFrame.NoFrame)
        self.hddResult.setFrameShadow(QtGui.QFrame.Sunken)
        self.hddResult.setAlignment(QtCore.Qt.AlignCenter)
        self.hddResult.setObjectName(_fromUtf8("hddResult"))
        self.usbResult = QtGui.QLabel(SkedYes)
        self.usbResult.setGeometry(QtCore.QRect(360, 250, 66, 28))
        self.usbResult.setMouseTracking(False)
        self.usbResult.setAutoFillBackground(True)
        self.usbResult.setInputMethodHints(QtCore.Qt.ImhPreferUppercase)
        self.usbResult.setFrameShape(QtGui.QFrame.NoFrame)
        self.usbResult.setFrameShadow(QtGui.QFrame.Sunken)
        self.usbResult.setAlignment(QtCore.Qt.AlignCenter)
        self.usbResult.setObjectName(_fromUtf8("usbResult"))
        self.smartcardResult = QtGui.QLabel(SkedYes)
        self.smartcardResult.setGeometry(QtCore.QRect(360, 290, 66, 28))
        self.smartcardResult.setMouseTracking(False)
        self.smartcardResult.setAutoFillBackground(True)
        self.smartcardResult.setInputMethodHints(QtCore.Qt.ImhPreferUppercase)
        self.smartcardResult.setFrameShape(QtGui.QFrame.NoFrame)
        self.smartcardResult.setFrameShadow(QtGui.QFrame.Sunken)
        self.smartcardResult.setAlignment(QtCore.Qt.AlignCenter)
        self.smartcardResult.setObjectName(_fromUtf8("smartcardResult"))
        self.disconnectButton = QtGui.QPushButton(SkedYes)
        self.disconnectButton.setGeometry(QtCore.QRect(920, 140, 140, 50))
        self.disconnectButton.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.disconnectButton.setObjectName(_fromUtf8("disconnectButton"))
        self.labelTemperature = QtGui.QLabel(SkedYes)
        self.labelTemperature.setGeometry(QtCore.QRect(850, 636, 111, 31))
        self.labelTemperature.setObjectName(_fromUtf8("labelTemperature"))
        self.labelTemperatureValue = QtGui.QLabel(SkedYes)
        self.labelTemperatureValue.setGeometry(QtCore.QRect(970, 640, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelTemperatureValue.setFont(font)
        self.labelTemperatureValue.setObjectName(_fromUtf8("labelTemperatureValue"))
        self.tunerStartButton = QtGui.QPushButton(SkedYes)
        self.tunerStartButton.setGeometry(QtCore.QRect(660, 170, 66, 28))
        self.tunerStartButton.setObjectName(_fromUtf8("tunerStartButton"))
        self.hddStartButton = QtGui.QPushButton(SkedYes)
        self.hddStartButton.setGeometry(QtCore.QRect(660, 210, 66, 28))
        self.hddStartButton.setObjectName(_fromUtf8("hddStartButton"))
        self.usbStartButton = QtGui.QPushButton(SkedYes)
        self.usbStartButton.setGeometry(QtCore.QRect(660, 250, 66, 28))
        self.usbStartButton.setObjectName(_fromUtf8("usbStartButton"))
        self.smartcardStartButton = QtGui.QPushButton(SkedYes)
        self.smartcardStartButton.setGeometry(QtCore.QRect(660, 290, 66, 28))
        self.smartcardStartButton.setObjectName(_fromUtf8("smartcardStartButton"))
        self.usbStopButton = QtGui.QPushButton(SkedYes)
        self.usbStopButton.setGeometry(QtCore.QRect(760, 250, 66, 28))
        self.usbStopButton.setObjectName(_fromUtf8("usbStopButton"))
        self.smartcardStopButton = QtGui.QPushButton(SkedYes)
        self.smartcardStopButton.setGeometry(QtCore.QRect(760, 290, 66, 28))
        self.smartcardStopButton.setObjectName(_fromUtf8("smartcardStopButton"))
        self.tunerStopButton = QtGui.QPushButton(SkedYes)
        self.tunerStopButton.setGeometry(QtCore.QRect(760, 170, 66, 28))
        self.tunerStopButton.setObjectName(_fromUtf8("tunerStopButton"))
        self.hddStopButton = QtGui.QPushButton(SkedYes)
        self.hddStopButton.setGeometry(QtCore.QRect(760, 210, 66, 28))
        self.hddStopButton.setObjectName(_fromUtf8("hddStopButton"))
        self.autoTestButton = QtGui.QRadioButton(SkedYes)
        self.autoTestButton.setGeometry(QtCore.QRect(700, 120, 116, 28))
        self.autoTestButton.setIconSize(QtCore.QSize(20, 20))
        self.autoTestButton.setAutoRepeat(False)
        self.autoTestButton.setAutoExclusive(False)
        self.autoTestButton.setObjectName(_fromUtf8("autoTestButton"))
        self.fanStopButton = QtGui.QPushButton(SkedYes)
        self.fanStopButton.setGeometry(QtCore.QRect(760, 330, 66, 28))
        self.fanStopButton.setObjectName(_fromUtf8("fanStopButton"))
        self.fanStartButton = QtGui.QPushButton(SkedYes)
        self.fanStartButton.setGeometry(QtCore.QRect(660, 330, 66, 28))
        self.fanStartButton.setObjectName(_fromUtf8("fanStartButton"))
        self.fanResult = QtGui.QLabel(SkedYes)
        self.fanResult.setGeometry(QtCore.QRect(360, 330, 66, 28))
        self.fanResult.setMouseTracking(False)
        self.fanResult.setAutoFillBackground(True)
        self.fanResult.setInputMethodHints(QtCore.Qt.ImhPreferUppercase)
        self.fanResult.setFrameShape(QtGui.QFrame.NoFrame)
        self.fanResult.setFrameShadow(QtGui.QFrame.Sunken)
        self.fanResult.setAlignment(QtCore.Qt.AlignCenter)
        self.fanResult.setObjectName(_fromUtf8("fanResult"))
        self.fanTestProgressbar = QtGui.QProgressBar(SkedYes)
        self.fanTestProgressbar.setGeometry(QtCore.QRect(230, 330, 120, 28))
        self.fanTestProgressbar.setProperty("value", 5)
        self.fanTestProgressbar.setObjectName(_fromUtf8("fanTestProgressbar"))
        self.labelFanTest = QtGui.QLabel(SkedYes)
        self.labelFanTest.setGeometry(QtCore.QRect(50, 330, 160, 28))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelFanTest.setFont(font)
        self.labelFanTest.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.labelFanTest.setFrameShape(QtGui.QFrame.WinPanel)
        self.labelFanTest.setIndent(-1)
        self.labelFanTest.setObjectName(_fromUtf8("labelFanTest"))
        self.fpStartButton = QtGui.QPushButton(SkedYes)
        self.fpStartButton.setGeometry(QtCore.QRect(660, 410, 66, 28))
        self.fpStartButton.setObjectName(_fromUtf8("fpStartButton"))
        self.labelFpTest = QtGui.QLabel(SkedYes)
        self.labelFpTest.setGeometry(QtCore.QRect(50, 410, 160, 28))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelFpTest.setFont(font)
        self.labelFpTest.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.labelFpTest.setFrameShape(QtGui.QFrame.WinPanel)
        self.labelFpTest.setIndent(-1)
        self.labelFpTest.setObjectName(_fromUtf8("labelFpTest"))
        self.fpTestProgressbar = QtGui.QProgressBar(SkedYes)
        self.fpTestProgressbar.setGeometry(QtCore.QRect(230, 410, 120, 28))
        self.fpTestProgressbar.setProperty("value", 5)
        self.fpTestProgressbar.setObjectName(_fromUtf8("fpTestProgressbar"))
        self.fpResult = QtGui.QLabel(SkedYes)
        self.fpResult.setGeometry(QtCore.QRect(360, 410, 66, 28))
        self.fpResult.setMouseTracking(False)
        self.fpResult.setAutoFillBackground(True)
        self.fpResult.setInputMethodHints(QtCore.Qt.ImhPreferUppercase)
        self.fpResult.setFrameShape(QtGui.QFrame.NoFrame)
        self.fpResult.setFrameShadow(QtGui.QFrame.Sunken)
        self.fpResult.setAlignment(QtCore.Qt.AlignCenter)
        self.fpResult.setObjectName(_fromUtf8("fpResult"))
        self.fpStopButton = QtGui.QPushButton(SkedYes)
        self.fpStopButton.setGeometry(QtCore.QRect(760, 410, 66, 28))
        self.fpStopButton.setObjectName(_fromUtf8("fpStopButton"))
        self.ledTestProgressbar = QtGui.QProgressBar(SkedYes)
        self.ledTestProgressbar.setGeometry(QtCore.QRect(230, 370, 120, 28))
        self.ledTestProgressbar.setProperty("value", 5)
        self.ledTestProgressbar.setObjectName(_fromUtf8("ledTestProgressbar"))
        self.labelLedTest = QtGui.QLabel(SkedYes)
        self.labelLedTest.setGeometry(QtCore.QRect(50, 370, 160, 28))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelLedTest.setFont(font)
        self.labelLedTest.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.labelLedTest.setFrameShape(QtGui.QFrame.WinPanel)
        self.labelLedTest.setIndent(-1)
        self.labelLedTest.setObjectName(_fromUtf8("labelLedTest"))
        self.ledResult = QtGui.QLabel(SkedYes)
        self.ledResult.setGeometry(QtCore.QRect(360, 370, 66, 28))
        self.ledResult.setMouseTracking(False)
        self.ledResult.setAutoFillBackground(True)
        self.ledResult.setInputMethodHints(QtCore.Qt.ImhPreferUppercase)
        self.ledResult.setFrameShape(QtGui.QFrame.NoFrame)
        self.ledResult.setFrameShadow(QtGui.QFrame.Sunken)
        self.ledResult.setAlignment(QtCore.Qt.AlignCenter)
        self.ledResult.setObjectName(_fromUtf8("ledResult"))
        self.ledStopButton = QtGui.QPushButton(SkedYes)
        self.ledStopButton.setGeometry(QtCore.QRect(760, 370, 66, 28))
        self.ledStopButton.setObjectName(_fromUtf8("ledStopButton"))
        self.ledStartButton = QtGui.QPushButton(SkedYes)
        self.ledStartButton.setGeometry(QtCore.QRect(660, 370, 66, 28))
        self.ledStartButton.setObjectName(_fromUtf8("ledStartButton"))
        self.handleHDCPLabel = QtGui.QLabel(SkedYes)
        self.handleHDCPLabel.setGeometry(QtCore.QRect(50, 620, 120, 28))
        self.handleHDCPLabel.setObjectName(_fromUtf8("handleHDCPLabel"))
        self.handleAppSwUpdate = QtGui.QLabel(SkedYes)
        self.handleAppSwUpdate.setGeometry(QtCore.QRect(50, 660, 120, 28))
        self.handleAppSwUpdate.setObjectName(_fromUtf8("handleAppSwUpdate"))
        self.hdcpStartButton = QtGui.QPushButton(SkedYes)
        self.hdcpStartButton.setGeometry(QtCore.QRect(170, 620, 66, 28))
        self.hdcpStartButton.setObjectName(_fromUtf8("hdcpStartButton"))
        self.uiUpdateStartButton = QtGui.QPushButton(SkedYes)
        self.uiUpdateStartButton.setGeometry(QtCore.QRect(170, 660, 66, 28))
        self.uiUpdateStartButton.setObjectName(_fromUtf8("uiUpdateStartButton"))
        self.statusLabel = QtGui.QLabel(SkedYes)
        self.statusLabel.setGeometry(QtCore.QRect(50, 700, 66, 28))
        self.statusLabel.setObjectName(_fromUtf8("statusLabel"))
        self.statusMsgLabel = QtGui.QLabel(SkedYes)
        self.statusMsgLabel.setGeometry(QtCore.QRect(110, 700, 400, 28))
        self.statusMsgLabel.setText(_fromUtf8(""))
        self.statusMsgLabel.setObjectName(_fromUtf8("statusMsgLabel"))
        self.fanSpeed = QtGui.QLabel(SkedYes)
        self.fanSpeed.setGeometry(QtCore.QRect(420, 330, 171, 28))
        self.fanSpeed.setMouseTracking(False)
        self.fanSpeed.setAutoFillBackground(True)
        self.fanSpeed.setInputMethodHints(QtCore.Qt.ImhPreferUppercase)
        self.fanSpeed.setFrameShape(QtGui.QFrame.NoFrame)
        self.fanSpeed.setFrameShadow(QtGui.QFrame.Sunken)
        self.fanSpeed.setAlignment(QtCore.Qt.AlignCenter)
        self.fanSpeed.setObjectName(_fromUtf8("fanSpeed"))
        self.lnbVoltage13 = QtGui.QRadioButton(SkedYes)
        self.lnbVoltage13.setGeometry(QtCore.QRect(424, 170, 61, 28))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.lnbVoltage13.setFont(font)
        self.lnbVoltage13.setIconSize(QtCore.QSize(12, 12))
        self.lnbVoltage13.setChecked(True)
        self.lnbVoltage13.setObjectName(_fromUtf8("lnbVoltage13"))
        self.lnbVoltage18 = QtGui.QRadioButton(SkedYes)
        self.lnbVoltage18.setGeometry(QtCore.QRect(484, 170, 61, 28))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.lnbVoltage18.setFont(font)
        self.lnbVoltage18.setIconSize(QtCore.QSize(12, 12))
        self.lnbVoltage18.setObjectName(_fromUtf8("lnbVoltage18"))
        self.diseqc22Khz = QtGui.QRadioButton(SkedYes)
        self.diseqc22Khz.setGeometry(QtCore.QRect(544, 170, 111, 28))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.diseqc22Khz.setFont(font)
        self.diseqc22Khz.setIconSize(QtCore.QSize(12, 12))
        self.diseqc22Khz.setAutoRepeat(False)
        self.diseqc22Khz.setAutoExclusive(False)
        self.diseqc22Khz.setObjectName(_fromUtf8("diseqc22Khz"))

        self.retranslateUi(SkedYes)
        QtCore.QObject.connect(self.exitButton, QtCore.SIGNAL(_fromUtf8("clicked()")), SkedYes.close)
        QtCore.QObject.connect(self.connectToStbButton, QtCore.SIGNAL(_fromUtf8("clicked()")), self.labelHddTest.setFocus)
        QtCore.QObject.connect(self.disconnectButton, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.labelHddTest.update)
        QtCore.QMetaObject.connectSlotsByName(SkedYes)

    def retranslateUi(self, SkedYes):
        SkedYes.setWindowTitle(_translate("SkedYes", "SKED YES V0.1", None))
        SkedYes.setWhatsThis(_translate("SkedYes", "Tuner Test", None))
        self.header.setText(_translate("SkedYes", "SKED YES ", None))
        self.telnetConnection.setText(_translate("SkedYes", "Telnet Connection Status:", None))
        self.stbSwVer.setText(_translate("SkedYes", "STB SW Version:", None))
        self.stbEth0Mac.setText(_translate("SkedYes", "ETH0 MAC", None))
        self.stbWiFiMac.setText(_translate("SkedYes", "WiFi MAC", None))
        self.modelInfo.setText(_translate("SkedYes", "Model:", None))
        self.hddSn.setText(_translate("SkedYes", "HDD SN:", None))
        self.connectToStbButton.setText(_translate("SkedYes", "Connect", None))
        self.exitButton.setText(_translate("SkedYes", "Exit", None))
        self.labelTunerTest.setText(_translate("SkedYes", "Tuner Test 1", None))
        self.labelHddTest.setText(_translate("SkedYes", "HDD Test", None))
        self.labelUsbTest.setText(_translate("SkedYes", "USB Test", None))
        self.labelSmartcardTest.setText(_translate("SkedYes", "Smartcard ", None))
        self.tunerResult.setText(_translate("SkedYes", "PASS", None))
        self.hddResult.setText(_translate("SkedYes", "PASS", None))
        self.usbResult.setText(_translate("SkedYes", "PASS", None))
        self.smartcardResult.setText(_translate("SkedYes", "PASS", None))
        self.disconnectButton.setText(_translate("SkedYes", "Disconnect", None))
        self.labelTemperature.setText(_translate("SkedYes", "Temperature :", None))
        self.labelTemperatureValue.setText(_translate("SkedYes", "30 C", None))
        self.tunerStartButton.setText(_translate("SkedYes", "Start", None))
        self.hddStartButton.setText(_translate("SkedYes", "Start", None))
        self.usbStartButton.setText(_translate("SkedYes", "Start", None))
        self.smartcardStartButton.setText(_translate("SkedYes", "Start", None))
        self.usbStopButton.setText(_translate("SkedYes", "Stop", None))
        self.smartcardStopButton.setText(_translate("SkedYes", "Stop", None))
        self.tunerStopButton.setText(_translate("SkedYes", "Stop", None))
        self.hddStopButton.setText(_translate("SkedYes", "Stop", None))
        self.autoTestButton.setText(_translate("SkedYes", "Auto Test", None))
        self.fanStopButton.setText(_translate("SkedYes", "Stop", None))
        self.fanStartButton.setText(_translate("SkedYes", "Start", None))
        self.fanResult.setText(_translate("SkedYes", "PASS", None))
        self.labelFanTest.setText(_translate("SkedYes", "Fan Test", None))
        self.fpStartButton.setText(_translate("SkedYes", "Start", None))
        self.labelFpTest.setText(_translate("SkedYes", "VFD Test", None))
        self.fpResult.setText(_translate("SkedYes", "PASS", None))
        self.fpStopButton.setText(_translate("SkedYes", "Stop", None))
        self.labelLedTest.setText(_translate("SkedYes", "Led Test", None))
        self.ledResult.setText(_translate("SkedYes", "PASS", None))
        self.ledStopButton.setText(_translate("SkedYes", "Stop", None))
        self.ledStartButton.setText(_translate("SkedYes", "Start", None))
        self.handleHDCPLabel.setText(_translate("SkedYes", "Program HDCP", None))
        self.handleAppSwUpdate.setText(_translate("SkedYes", "Update UI", None))
        self.hdcpStartButton.setText(_translate("SkedYes", "Start", None))
        self.uiUpdateStartButton.setText(_translate("SkedYes", "Start", None))
        self.statusLabel.setText(_translate("SkedYes", "Status :", None))
        self.fanSpeed.setText(_translate("SkedYes", "FAN: Speed 00000", None))
        self.lnbVoltage13.setText(_translate("SkedYes", "13V", None))
        self.lnbVoltage18.setText(_translate("SkedYes", "18V", None))
        self.diseqc22Khz.setText(_translate("SkedYes", "22K ON/OFF", None))

