# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'skqt.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_SkedYes(object):
    def setupUi(self, SkedYes):
        SkedYes.setObjectName(_fromUtf8("SkedYes"))
        SkedYes.resize(1024, 768)
        SkedYes.setFocusPolicy(QtCore.Qt.ClickFocus)
        SkedYes.setAutoFillBackground(True)
        SkedYes.setStyleSheet(_fromUtf8(""))
        self.header = QtGui.QLabel(SkedYes)
        self.header.setGeometry(QtCore.QRect(40, 40, 180, 24))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Black"))
        font.setPointSize(22)
        self.header.setFont(font)
        self.header.setTextFormat(QtCore.Qt.AutoText)
        self.header.setObjectName(_fromUtf8("header"))
        self.telnetConnection = QtGui.QLabel(SkedYes)
        self.telnetConnection.setGeometry(QtCore.QRect(40, 80, 260, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.telnetConnection.setFont(font)
        self.telnetConnection.setObjectName(_fromUtf8("telnetConnection"))
        self.stbSwVer = QtGui.QLabel(SkedYes)
        self.stbSwVer.setGeometry(QtCore.QRect(490, 540, 80, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.stbSwVer.setFont(font)
        self.stbSwVer.setObjectName(_fromUtf8("stbSwVer"))
        self.progressBar = QtGui.QProgressBar(SkedYes)
        self.progressBar.setGeometry(QtCore.QRect(40, 690, 680, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.progressBar.setFont(font)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.telnetEditorOuput = QtGui.QTextEdit(SkedYes)
        self.telnetEditorOuput.setGeometry(QtCore.QRect(40, 570, 440, 111))
        self.telnetEditorOuput.setObjectName(_fromUtf8("telnetEditorOuput"))
        self.stbEth0Mac = QtGui.QLabel(SkedYes)
        self.stbEth0Mac.setGeometry(QtCore.QRect(490, 570, 80, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.stbEth0Mac.setFont(font)
        self.stbEth0Mac.setObjectName(_fromUtf8("stbEth0Mac"))
        self.stbWiFiMac = QtGui.QLabel(SkedYes)
        self.stbWiFiMac.setGeometry(QtCore.QRect(490, 600, 80, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.stbWiFiMac.setFont(font)
        self.stbWiFiMac.setObjectName(_fromUtf8("stbWiFiMac"))
        self.modelInfo = QtGui.QLabel(SkedYes)
        self.modelInfo.setGeometry(QtCore.QRect(490, 630, 80, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.modelInfo.setFont(font)
        self.modelInfo.setObjectName(_fromUtf8("modelInfo"))
        self.textStbSwVersion = QtGui.QTextEdit(SkedYes)
        self.textStbSwVersion.setGeometry(QtCore.QRect(580, 540, 140, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.textStbSwVersion.setFont(font)
        self.textStbSwVersion.setReadOnly(True)
        self.textStbSwVersion.setObjectName(_fromUtf8("textStbSwVersion"))
        self.textStbEth0Mac = QtGui.QTextEdit(SkedYes)
        self.textStbEth0Mac.setGeometry(QtCore.QRect(580, 570, 140, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.textStbEth0Mac.setFont(font)
        self.textStbEth0Mac.setReadOnly(True)
        self.textStbEth0Mac.setObjectName(_fromUtf8("textStbEth0Mac"))
        self.textStbModel = QtGui.QTextEdit(SkedYes)
        self.textStbModel.setGeometry(QtCore.QRect(580, 630, 140, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.textStbModel.setFont(font)
        self.textStbModel.setReadOnly(True)
        self.textStbModel.setAcceptRichText(True)
        self.textStbModel.setTextInteractionFlags(QtCore.Qt.TextSelectableByMouse)
        self.textStbModel.setObjectName(_fromUtf8("textStbModel"))
        self.textStbWifiMac = QtGui.QTextEdit(SkedYes)
        self.textStbWifiMac.setGeometry(QtCore.QRect(580, 600, 140, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.textStbWifiMac.setFont(font)
        self.textStbWifiMac.setReadOnly(True)
        self.textStbWifiMac.setObjectName(_fromUtf8("textStbWifiMac"))
        self.textStbHddSn = QtGui.QTextEdit(SkedYes)
        self.textStbHddSn.setGeometry(QtCore.QRect(580, 660, 140, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.textStbHddSn.setFont(font)
        self.textStbHddSn.setReadOnly(True)
        self.textStbHddSn.setObjectName(_fromUtf8("textStbHddSn"))
        self.hddSn = QtGui.QLabel(SkedYes)
        self.hddSn.setGeometry(QtCore.QRect(490, 660, 80, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.hddSn.setFont(font)
        self.hddSn.setObjectName(_fromUtf8("hddSn"))
        self.dateAndTime = QtGui.QLabel(SkedYes)
        self.dateAndTime.setGeometry(QtCore.QRect(740, 10, 260, 24))
        self.dateAndTime.setText(_fromUtf8(""))
        self.dateAndTime.setObjectName(_fromUtf8("dateAndTime"))
        self.connectToStbButton = QtGui.QPushButton(SkedYes)
        self.connectToStbButton.setGeometry(QtCore.QRect(610, 20, 80, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.connectToStbButton.setFont(font)
        self.connectToStbButton.setObjectName(_fromUtf8("connectToStbButton"))
        self.exitButton = QtGui.QPushButton(SkedYes)
        self.exitButton.setGeometry(QtCore.QRect(610, 100, 80, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.exitButton.setFont(font)
        self.exitButton.setObjectName(_fromUtf8("exitButton"))
        self.labelHddTest = QtGui.QLabel(SkedYes)
        self.labelHddTest.setGeometry(QtCore.QRect(40, 120, 90, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.labelHddTest.setFont(font)
        self.labelHddTest.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.labelHddTest.setStyleSheet(_fromUtf8(""))
        self.labelHddTest.setFrameShape(QtGui.QFrame.WinPanel)
        self.labelHddTest.setIndent(-1)
        self.labelHddTest.setObjectName(_fromUtf8("labelHddTest"))
        self.labelUsbTest = QtGui.QLabel(SkedYes)
        self.labelUsbTest.setGeometry(QtCore.QRect(40, 150, 90, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.labelUsbTest.setFont(font)
        self.labelUsbTest.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.labelUsbTest.setFrameShape(QtGui.QFrame.WinPanel)
        self.labelUsbTest.setIndent(-1)
        self.labelUsbTest.setObjectName(_fromUtf8("labelUsbTest"))
        self.labelSmartcardTest = QtGui.QLabel(SkedYes)
        self.labelSmartcardTest.setGeometry(QtCore.QRect(40, 180, 90, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.labelSmartcardTest.setFont(font)
        self.labelSmartcardTest.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.labelSmartcardTest.setFrameShape(QtGui.QFrame.WinPanel)
        self.labelSmartcardTest.setIndent(-1)
        self.labelSmartcardTest.setObjectName(_fromUtf8("labelSmartcardTest"))
        self.hddTestProgressBar = QtGui.QProgressBar(SkedYes)
        self.hddTestProgressBar.setGeometry(QtCore.QRect(140, 120, 120, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.hddTestProgressBar.setFont(font)
        self.hddTestProgressBar.setProperty("value", 5)
        self.hddTestProgressBar.setObjectName(_fromUtf8("hddTestProgressBar"))
        self.usbTestProgressBar = QtGui.QProgressBar(SkedYes)
        self.usbTestProgressBar.setGeometry(QtCore.QRect(140, 150, 120, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.usbTestProgressBar.setFont(font)
        self.usbTestProgressBar.setProperty("value", 5)
        self.usbTestProgressBar.setObjectName(_fromUtf8("usbTestProgressBar"))
        self.smartcardTestProgressbar = QtGui.QProgressBar(SkedYes)
        self.smartcardTestProgressbar.setGeometry(QtCore.QRect(140, 180, 120, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.smartcardTestProgressbar.setFont(font)
        self.smartcardTestProgressbar.setProperty("value", 5)
        self.smartcardTestProgressbar.setObjectName(_fromUtf8("smartcardTestProgressbar"))
        self.hddResult = QtGui.QLabel(SkedYes)
        self.hddResult.setGeometry(QtCore.QRect(270, 120, 48, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.hddResult.setFont(font)
        self.hddResult.setMouseTracking(False)
        self.hddResult.setAutoFillBackground(True)
        self.hddResult.setInputMethodHints(QtCore.Qt.ImhPreferUppercase)
        self.hddResult.setFrameShape(QtGui.QFrame.NoFrame)
        self.hddResult.setFrameShadow(QtGui.QFrame.Sunken)
        self.hddResult.setAlignment(QtCore.Qt.AlignCenter)
        self.hddResult.setObjectName(_fromUtf8("hddResult"))
        self.usbResult = QtGui.QLabel(SkedYes)
        self.usbResult.setGeometry(QtCore.QRect(270, 150, 48, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.usbResult.setFont(font)
        self.usbResult.setMouseTracking(False)
        self.usbResult.setAutoFillBackground(True)
        self.usbResult.setInputMethodHints(QtCore.Qt.ImhPreferUppercase)
        self.usbResult.setFrameShape(QtGui.QFrame.NoFrame)
        self.usbResult.setFrameShadow(QtGui.QFrame.Sunken)
        self.usbResult.setAlignment(QtCore.Qt.AlignCenter)
        self.usbResult.setObjectName(_fromUtf8("usbResult"))
        self.smartcardResult = QtGui.QLabel(SkedYes)
        self.smartcardResult.setGeometry(QtCore.QRect(270, 180, 48, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.smartcardResult.setFont(font)
        self.smartcardResult.setMouseTracking(False)
        self.smartcardResult.setAutoFillBackground(True)
        self.smartcardResult.setInputMethodHints(QtCore.Qt.ImhPreferUppercase)
        self.smartcardResult.setFrameShape(QtGui.QFrame.NoFrame)
        self.smartcardResult.setFrameShadow(QtGui.QFrame.Sunken)
        self.smartcardResult.setAlignment(QtCore.Qt.AlignCenter)
        self.smartcardResult.setObjectName(_fromUtf8("smartcardResult"))
        self.disconnectButton = QtGui.QPushButton(SkedYes)
        self.disconnectButton.setGeometry(QtCore.QRect(610, 60, 80, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.disconnectButton.setFont(font)
        self.disconnectButton.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.disconnectButton.setObjectName(_fromUtf8("disconnectButton"))
        self.labelTemperature = QtGui.QLabel(SkedYes)
        self.labelTemperature.setGeometry(QtCore.QRect(510, 510, 80, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.labelTemperature.setFont(font)
        self.labelTemperature.setObjectName(_fromUtf8("labelTemperature"))
        self.labelTemperatureValue = QtGui.QLabel(SkedYes)
        self.labelTemperatureValue.setGeometry(QtCore.QRect(580, 510, 60, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.labelTemperatureValue.setFont(font)
        self.labelTemperatureValue.setObjectName(_fromUtf8("labelTemperatureValue"))
        self.hddStartButton = QtGui.QPushButton(SkedYes)
        self.hddStartButton.setGeometry(QtCore.QRect(440, 120, 60, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.hddStartButton.setFont(font)
        self.hddStartButton.setObjectName(_fromUtf8("hddStartButton"))
        self.usbStartButton = QtGui.QPushButton(SkedYes)
        self.usbStartButton.setGeometry(QtCore.QRect(440, 150, 60, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.usbStartButton.setFont(font)
        self.usbStartButton.setObjectName(_fromUtf8("usbStartButton"))
        self.smartcardStartButton = QtGui.QPushButton(SkedYes)
        self.smartcardStartButton.setGeometry(QtCore.QRect(440, 180, 60, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.smartcardStartButton.setFont(font)
        self.smartcardStartButton.setObjectName(_fromUtf8("smartcardStartButton"))
        self.usbStopButton = QtGui.QPushButton(SkedYes)
        self.usbStopButton.setGeometry(QtCore.QRect(510, 150, 60, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.usbStopButton.setFont(font)
        self.usbStopButton.setObjectName(_fromUtf8("usbStopButton"))
        self.smartcardStopButton = QtGui.QPushButton(SkedYes)
        self.smartcardStopButton.setGeometry(QtCore.QRect(510, 180, 60, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.smartcardStopButton.setFont(font)
        self.smartcardStopButton.setObjectName(_fromUtf8("smartcardStopButton"))
        self.hddStopButton = QtGui.QPushButton(SkedYes)
        self.hddStopButton.setGeometry(QtCore.QRect(510, 120, 60, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.hddStopButton.setFont(font)
        self.hddStopButton.setObjectName(_fromUtf8("hddStopButton"))
        self.autoTestButton = QtGui.QRadioButton(SkedYes)
        self.autoTestButton.setGeometry(QtCore.QRect(330, 80, 100, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.autoTestButton.setFont(font)
        self.autoTestButton.setIconSize(QtCore.QSize(20, 20))
        self.autoTestButton.setAutoRepeat(False)
        self.autoTestButton.setAutoExclusive(False)
        self.autoTestButton.setObjectName(_fromUtf8("autoTestButton"))
        self.fanStopButton = QtGui.QPushButton(SkedYes)
        self.fanStopButton.setGeometry(QtCore.QRect(510, 210, 60, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.fanStopButton.setFont(font)
        self.fanStopButton.setObjectName(_fromUtf8("fanStopButton"))
        self.fanStartButton = QtGui.QPushButton(SkedYes)
        self.fanStartButton.setGeometry(QtCore.QRect(440, 210, 60, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.fanStartButton.setFont(font)
        self.fanStartButton.setObjectName(_fromUtf8("fanStartButton"))
        self.fanResult = QtGui.QLabel(SkedYes)
        self.fanResult.setGeometry(QtCore.QRect(270, 210, 48, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.fanResult.setFont(font)
        self.fanResult.setMouseTracking(False)
        self.fanResult.setAutoFillBackground(True)
        self.fanResult.setInputMethodHints(QtCore.Qt.ImhPreferUppercase)
        self.fanResult.setFrameShape(QtGui.QFrame.NoFrame)
        self.fanResult.setFrameShadow(QtGui.QFrame.Sunken)
        self.fanResult.setAlignment(QtCore.Qt.AlignCenter)
        self.fanResult.setObjectName(_fromUtf8("fanResult"))
        self.fanTestProgressbar = QtGui.QProgressBar(SkedYes)
        self.fanTestProgressbar.setGeometry(QtCore.QRect(140, 210, 120, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.fanTestProgressbar.setFont(font)
        self.fanTestProgressbar.setProperty("value", 5)
        self.fanTestProgressbar.setObjectName(_fromUtf8("fanTestProgressbar"))
        self.labelFanTest = QtGui.QLabel(SkedYes)
        self.labelFanTest.setGeometry(QtCore.QRect(40, 210, 90, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.labelFanTest.setFont(font)
        self.labelFanTest.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.labelFanTest.setFrameShape(QtGui.QFrame.WinPanel)
        self.labelFanTest.setIndent(-1)
        self.labelFanTest.setObjectName(_fromUtf8("labelFanTest"))
        self.fpStartButton = QtGui.QPushButton(SkedYes)
        self.fpStartButton.setGeometry(QtCore.QRect(440, 300, 60, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.fpStartButton.setFont(font)
        self.fpStartButton.setObjectName(_fromUtf8("fpStartButton"))
        self.labelFpTest = QtGui.QLabel(SkedYes)
        self.labelFpTest.setGeometry(QtCore.QRect(40, 300, 90, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.labelFpTest.setFont(font)
        self.labelFpTest.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.labelFpTest.setFrameShape(QtGui.QFrame.WinPanel)
        self.labelFpTest.setIndent(-1)
        self.labelFpTest.setObjectName(_fromUtf8("labelFpTest"))
        self.fpTestProgressbar = QtGui.QProgressBar(SkedYes)
        self.fpTestProgressbar.setGeometry(QtCore.QRect(140, 300, 120, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.fpTestProgressbar.setFont(font)
        self.fpTestProgressbar.setProperty("value", 5)
        self.fpTestProgressbar.setObjectName(_fromUtf8("fpTestProgressbar"))
        self.fpResult = QtGui.QLabel(SkedYes)
        self.fpResult.setGeometry(QtCore.QRect(270, 300, 48, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.fpResult.setFont(font)
        self.fpResult.setMouseTracking(False)
        self.fpResult.setAutoFillBackground(True)
        self.fpResult.setInputMethodHints(QtCore.Qt.ImhPreferUppercase)
        self.fpResult.setFrameShape(QtGui.QFrame.NoFrame)
        self.fpResult.setFrameShadow(QtGui.QFrame.Sunken)
        self.fpResult.setAlignment(QtCore.Qt.AlignCenter)
        self.fpResult.setObjectName(_fromUtf8("fpResult"))
        self.fpStopButton = QtGui.QPushButton(SkedYes)
        self.fpStopButton.setGeometry(QtCore.QRect(510, 300, 60, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.fpStopButton.setFont(font)
        self.fpStopButton.setObjectName(_fromUtf8("fpStopButton"))
        self.ledTestProgressbar = QtGui.QProgressBar(SkedYes)
        self.ledTestProgressbar.setGeometry(QtCore.QRect(140, 360, 120, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.ledTestProgressbar.setFont(font)
        self.ledTestProgressbar.setProperty("value", 5)
        self.ledTestProgressbar.setObjectName(_fromUtf8("ledTestProgressbar"))
        self.labelLedTest = QtGui.QLabel(SkedYes)
        self.labelLedTest.setGeometry(QtCore.QRect(40, 360, 90, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.labelLedTest.setFont(font)
        self.labelLedTest.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.labelLedTest.setFrameShape(QtGui.QFrame.WinPanel)
        self.labelLedTest.setIndent(-1)
        self.labelLedTest.setObjectName(_fromUtf8("labelLedTest"))
        self.ledResult = QtGui.QLabel(SkedYes)
        self.ledResult.setGeometry(QtCore.QRect(270, 360, 48, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.ledResult.setFont(font)
        self.ledResult.setMouseTracking(False)
        self.ledResult.setAutoFillBackground(True)
        self.ledResult.setInputMethodHints(QtCore.Qt.ImhPreferUppercase)
        self.ledResult.setFrameShape(QtGui.QFrame.NoFrame)
        self.ledResult.setFrameShadow(QtGui.QFrame.Sunken)
        self.ledResult.setAlignment(QtCore.Qt.AlignCenter)
        self.ledResult.setObjectName(_fromUtf8("ledResult"))
        self.ledStopButton = QtGui.QPushButton(SkedYes)
        self.ledStopButton.setGeometry(QtCore.QRect(510, 360, 60, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.ledStopButton.setFont(font)
        self.ledStopButton.setObjectName(_fromUtf8("ledStopButton"))
        self.ledStartButton = QtGui.QPushButton(SkedYes)
        self.ledStartButton.setGeometry(QtCore.QRect(440, 360, 60, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.ledStartButton.setFont(font)
        self.ledStartButton.setObjectName(_fromUtf8("ledStartButton"))
        self.handleHDCPLabel = QtGui.QLabel(SkedYes)
        self.handleHDCPLabel.setGeometry(QtCore.QRect(40, 480, 90, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.handleHDCPLabel.setFont(font)
        self.handleHDCPLabel.setObjectName(_fromUtf8("handleHDCPLabel"))
        self.handleAppSwUpdate = QtGui.QLabel(SkedYes)
        self.handleAppSwUpdate.setGeometry(QtCore.QRect(40, 510, 90, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.handleAppSwUpdate.setFont(font)
        self.handleAppSwUpdate.setObjectName(_fromUtf8("handleAppSwUpdate"))
        self.hdcpStartButton = QtGui.QPushButton(SkedYes)
        self.hdcpStartButton.setGeometry(QtCore.QRect(140, 480, 60, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.hdcpStartButton.setFont(font)
        self.hdcpStartButton.setObjectName(_fromUtf8("hdcpStartButton"))
        self.uiUpdateStartButton = QtGui.QPushButton(SkedYes)
        self.uiUpdateStartButton.setGeometry(QtCore.QRect(140, 510, 60, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.uiUpdateStartButton.setFont(font)
        self.uiUpdateStartButton.setObjectName(_fromUtf8("uiUpdateStartButton"))
        self.statusLabel = QtGui.QLabel(SkedYes)
        self.statusLabel.setGeometry(QtCore.QRect(40, 540, 60, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.statusLabel.setFont(font)
        self.statusLabel.setObjectName(_fromUtf8("statusLabel"))
        self.statusMsgLabel = QtGui.QLabel(SkedYes)
        self.statusMsgLabel.setGeometry(QtCore.QRect(140, 540, 340, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.statusMsgLabel.setFont(font)
        self.statusMsgLabel.setText(_fromUtf8(""))
        self.statusMsgLabel.setObjectName(_fromUtf8("statusMsgLabel"))
        self.fanSpeed = QtGui.QLabel(SkedYes)
        self.fanSpeed.setGeometry(QtCore.QRect(330, 210, 100, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.fanSpeed.setFont(font)
        self.fanSpeed.setMouseTracking(False)
        self.fanSpeed.setAutoFillBackground(True)
        self.fanSpeed.setInputMethodHints(QtCore.Qt.ImhPreferUppercase)
        self.fanSpeed.setFrameShape(QtGui.QFrame.NoFrame)
        self.fanSpeed.setFrameShadow(QtGui.QFrame.Sunken)
        self.fanSpeed.setObjectName(_fromUtf8("fanSpeed"))
        self.irStartButton = QtGui.QPushButton(SkedYes)
        self.irStartButton.setGeometry(QtCore.QRect(440, 390, 60, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.irStartButton.setFont(font)
        self.irStartButton.setObjectName(_fromUtf8("irStartButton"))
        self.labelIrTest = QtGui.QLabel(SkedYes)
        self.labelIrTest.setGeometry(QtCore.QRect(40, 390, 90, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.labelIrTest.setFont(font)
        self.labelIrTest.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.labelIrTest.setFrameShape(QtGui.QFrame.WinPanel)
        self.labelIrTest.setIndent(-1)
        self.labelIrTest.setObjectName(_fromUtf8("labelIrTest"))
        self.irStopButton = QtGui.QPushButton(SkedYes)
        self.irStopButton.setGeometry(QtCore.QRect(510, 390, 60, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.irStopButton.setFont(font)
        self.irStopButton.setObjectName(_fromUtf8("irStopButton"))
        self.irTestProgressbar = QtGui.QProgressBar(SkedYes)
        self.irTestProgressbar.setGeometry(QtCore.QRect(140, 390, 120, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.irTestProgressbar.setFont(font)
        self.irTestProgressbar.setProperty("value", 5)
        self.irTestProgressbar.setObjectName(_fromUtf8("irTestProgressbar"))
        self.irResult = QtGui.QLabel(SkedYes)
        self.irResult.setGeometry(QtCore.QRect(270, 390, 48, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.irResult.setFont(font)
        self.irResult.setMouseTracking(False)
        self.irResult.setAutoFillBackground(True)
        self.irResult.setInputMethodHints(QtCore.Qt.ImhPreferUppercase)
        self.irResult.setFrameShape(QtGui.QFrame.NoFrame)
        self.irResult.setFrameShadow(QtGui.QFrame.Sunken)
        self.irResult.setAlignment(QtCore.Qt.AlignCenter)
        self.irResult.setObjectName(_fromUtf8("irResult"))
        self.buttonStartButton = QtGui.QPushButton(SkedYes)
        self.buttonStartButton.setGeometry(QtCore.QRect(440, 330, 60, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.buttonStartButton.setFont(font)
        self.buttonStartButton.setObjectName(_fromUtf8("buttonStartButton"))
        self.labelButtonTest = QtGui.QLabel(SkedYes)
        self.labelButtonTest.setGeometry(QtCore.QRect(40, 330, 90, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.labelButtonTest.setFont(font)
        self.labelButtonTest.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.labelButtonTest.setFrameShape(QtGui.QFrame.WinPanel)
        self.labelButtonTest.setIndent(-1)
        self.labelButtonTest.setObjectName(_fromUtf8("labelButtonTest"))
        self.buttonStopButton = QtGui.QPushButton(SkedYes)
        self.buttonStopButton.setGeometry(QtCore.QRect(510, 330, 60, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.buttonStopButton.setFont(font)
        self.buttonStopButton.setObjectName(_fromUtf8("buttonStopButton"))
        self.buttonTestProgressbar = QtGui.QProgressBar(SkedYes)
        self.buttonTestProgressbar.setGeometry(QtCore.QRect(140, 330, 120, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.buttonTestProgressbar.setFont(font)
        self.buttonTestProgressbar.setProperty("value", 5)
        self.buttonTestProgressbar.setObjectName(_fromUtf8("buttonTestProgressbar"))
        self.buttonResult = QtGui.QLabel(SkedYes)
        self.buttonResult.setGeometry(QtCore.QRect(270, 330, 48, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.buttonResult.setFont(font)
        self.buttonResult.setMouseTracking(False)
        self.buttonResult.setAutoFillBackground(True)
        self.buttonResult.setInputMethodHints(QtCore.Qt.ImhPreferUppercase)
        self.buttonResult.setFrameShape(QtGui.QFrame.NoFrame)
        self.buttonResult.setFrameShadow(QtGui.QFrame.Sunken)
        self.buttonResult.setAlignment(QtCore.Qt.AlignCenter)
        self.buttonResult.setObjectName(_fromUtf8("buttonResult"))
        self.irKeysRecivce = QtGui.QLabel(SkedYes)
        self.irKeysRecivce.setGeometry(QtCore.QRect(330, 390, 100, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.irKeysRecivce.setFont(font)
        self.irKeysRecivce.setMouseTracking(False)
        self.irKeysRecivce.setAutoFillBackground(True)
        self.irKeysRecivce.setInputMethodHints(QtCore.Qt.ImhPreferUppercase)
        self.irKeysRecivce.setFrameShape(QtGui.QFrame.NoFrame)
        self.irKeysRecivce.setFrameShadow(QtGui.QFrame.Sunken)
        self.irKeysRecivce.setObjectName(_fromUtf8("irKeysRecivce"))
        self.buttonKeysRecivce = QtGui.QLabel(SkedYes)
        self.buttonKeysRecivce.setGeometry(QtCore.QRect(330, 330, 100, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.buttonKeysRecivce.setFont(font)
        self.buttonKeysRecivce.setMouseTracking(False)
        self.buttonKeysRecivce.setAutoFillBackground(True)
        self.buttonKeysRecivce.setInputMethodHints(QtCore.Qt.ImhPreferUppercase)
        self.buttonKeysRecivce.setFrameShape(QtGui.QFrame.NoFrame)
        self.buttonKeysRecivce.setFrameShadow(QtGui.QFrame.Sunken)
        self.buttonKeysRecivce.setObjectName(_fromUtf8("buttonKeysRecivce"))
        self.labelMacAddressInput = QtGui.QLabel(SkedYes)
        self.labelMacAddressInput.setGeometry(QtCore.QRect(40, 450, 90, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.labelMacAddressInput.setFont(font)
        self.labelMacAddressInput.setObjectName(_fromUtf8("labelMacAddressInput"))
        self.uiUpgradeResult = QtGui.QLabel(SkedYes)
        self.uiUpgradeResult.setGeometry(QtCore.QRect(270, 510, 48, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.uiUpgradeResult.setFont(font)
        self.uiUpgradeResult.setMouseTracking(False)
        self.uiUpgradeResult.setAutoFillBackground(True)
        self.uiUpgradeResult.setInputMethodHints(QtCore.Qt.ImhPreferUppercase)
        self.uiUpgradeResult.setFrameShape(QtGui.QFrame.NoFrame)
        self.uiUpgradeResult.setFrameShadow(QtGui.QFrame.Sunken)
        self.uiUpgradeResult.setAlignment(QtCore.Qt.AlignCenter)
        self.uiUpgradeResult.setObjectName(_fromUtf8("uiUpgradeResult"))
        self.hdcpKeyResult = QtGui.QLabel(SkedYes)
        self.hdcpKeyResult.setGeometry(QtCore.QRect(270, 480, 48, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.hdcpKeyResult.setFont(font)
        self.hdcpKeyResult.setMouseTracking(False)
        self.hdcpKeyResult.setAutoFillBackground(True)
        self.hdcpKeyResult.setInputMethodHints(QtCore.Qt.ImhPreferUppercase)
        self.hdcpKeyResult.setFrameShape(QtGui.QFrame.NoFrame)
        self.hdcpKeyResult.setFrameShadow(QtGui.QFrame.Sunken)
        self.hdcpKeyResult.setAlignment(QtCore.Qt.AlignCenter)
        self.hdcpKeyResult.setObjectName(_fromUtf8("hdcpKeyResult"))
        self.tunerStopButton = QtGui.QPushButton(SkedYes)
        self.tunerStopButton.setGeometry(QtCore.QRect(510, 270, 60, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.tunerStopButton.setFont(font)
        self.tunerStopButton.setObjectName(_fromUtf8("tunerStopButton"))
        self.tunerStartButton = QtGui.QPushButton(SkedYes)
        self.tunerStartButton.setGeometry(QtCore.QRect(440, 270, 60, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.tunerStartButton.setFont(font)
        self.tunerStartButton.setObjectName(_fromUtf8("tunerStartButton"))
        self.labelTunerTest = QtGui.QLabel(SkedYes)
        self.labelTunerTest.setGeometry(QtCore.QRect(40, 270, 91, 20))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 213, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(63, 191, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 113, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 212, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 213, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(63, 191, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 113, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 212, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 213, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(63, 191, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 113, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.labelTunerTest.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.labelTunerTest.setFont(font)
        self.labelTunerTest.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.labelTunerTest.setStyleSheet(_fromUtf8(""))
        self.labelTunerTest.setFrameShape(QtGui.QFrame.WinPanel)
        self.labelTunerTest.setIndent(-1)
        self.labelTunerTest.setObjectName(_fromUtf8("labelTunerTest"))
        self.tunerTestProgressBar = QtGui.QProgressBar(SkedYes)
        self.tunerTestProgressBar.setGeometry(QtCore.QRect(140, 270, 120, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.tunerTestProgressBar.setFont(font)
        self.tunerTestProgressBar.setProperty("value", 5)
        self.tunerTestProgressBar.setObjectName(_fromUtf8("tunerTestProgressBar"))
        self.tunerResult = QtGui.QLabel(SkedYes)
        self.tunerResult.setGeometry(QtCore.QRect(270, 270, 48, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.tunerResult.setFont(font)
        self.tunerResult.setMouseTracking(False)
        self.tunerResult.setAutoFillBackground(True)
        self.tunerResult.setInputMethodHints(QtCore.Qt.ImhPreferUppercase)
        self.tunerResult.setFrameShape(QtGui.QFrame.NoFrame)
        self.tunerResult.setFrameShadow(QtGui.QFrame.Sunken)
        self.tunerResult.setAlignment(QtCore.Qt.AlignCenter)
        self.tunerResult.setObjectName(_fromUtf8("tunerResult"))
        self.lnbTestProgressbar = QtGui.QProgressBar(SkedYes)
        self.lnbTestProgressbar.setGeometry(QtCore.QRect(140, 240, 120, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lnbTestProgressbar.setFont(font)
        self.lnbTestProgressbar.setProperty("value", 5)
        self.lnbTestProgressbar.setObjectName(_fromUtf8("lnbTestProgressbar"))
        self.lnbStopButton = QtGui.QPushButton(SkedYes)
        self.lnbStopButton.setGeometry(QtCore.QRect(510, 240, 60, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lnbStopButton.setFont(font)
        self.lnbStopButton.setObjectName(_fromUtf8("lnbStopButton"))
        self.labelLnbTest = QtGui.QLabel(SkedYes)
        self.labelLnbTest.setGeometry(QtCore.QRect(40, 240, 90, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.labelLnbTest.setFont(font)
        self.labelLnbTest.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.labelLnbTest.setFrameShape(QtGui.QFrame.WinPanel)
        self.labelLnbTest.setIndent(-1)
        self.labelLnbTest.setObjectName(_fromUtf8("labelLnbTest"))
        self.lnbValue = QtGui.QLabel(SkedYes)
        self.lnbValue.setGeometry(QtCore.QRect(330, 240, 100, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lnbValue.setFont(font)
        self.lnbValue.setMouseTracking(False)
        self.lnbValue.setAutoFillBackground(True)
        self.lnbValue.setInputMethodHints(QtCore.Qt.ImhPreferUppercase)
        self.lnbValue.setFrameShape(QtGui.QFrame.NoFrame)
        self.lnbValue.setFrameShadow(QtGui.QFrame.Sunken)
        self.lnbValue.setObjectName(_fromUtf8("lnbValue"))
        self.lnbResult = QtGui.QLabel(SkedYes)
        self.lnbResult.setGeometry(QtCore.QRect(270, 240, 48, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lnbResult.setFont(font)
        self.lnbResult.setMouseTracking(False)
        self.lnbResult.setAutoFillBackground(True)
        self.lnbResult.setInputMethodHints(QtCore.Qt.ImhPreferUppercase)
        self.lnbResult.setFrameShape(QtGui.QFrame.NoFrame)
        self.lnbResult.setFrameShadow(QtGui.QFrame.Sunken)
        self.lnbResult.setAlignment(QtCore.Qt.AlignCenter)
        self.lnbResult.setObjectName(_fromUtf8("lnbResult"))
        self.lnbStartButton = QtGui.QPushButton(SkedYes)
        self.lnbStartButton.setGeometry(QtCore.QRect(440, 240, 60, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lnbStartButton.setFont(font)
        self.lnbStartButton.setObjectName(_fromUtf8("lnbStartButton"))
        self.tunerLnbValue = QtGui.QLabel(SkedYes)
        self.tunerLnbValue.setGeometry(QtCore.QRect(330, 270, 100, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.tunerLnbValue.setFont(font)
        self.tunerLnbValue.setMouseTracking(False)
        self.tunerLnbValue.setAutoFillBackground(True)
        self.tunerLnbValue.setInputMethodHints(QtCore.Qt.ImhPreferUppercase)
        self.tunerLnbValue.setFrameShape(QtGui.QFrame.NoFrame)
        self.tunerLnbValue.setFrameShadow(QtGui.QFrame.Sunken)
        self.tunerLnbValue.setObjectName(_fromUtf8("tunerLnbValue"))
        self.macAddressInputValue = QtGui.QLabel(SkedYes)
        self.macAddressInputValue.setGeometry(QtCore.QRect(140, 450, 120, 20))
        self.macAddressInputValue.setText(_fromUtf8(""))
        self.macAddressInputValue.setObjectName(_fromUtf8("macAddressInputValue"))

        self.retranslateUi(SkedYes)
        QtCore.QObject.connect(self.exitButton, QtCore.SIGNAL(_fromUtf8("clicked()")), SkedYes.close)
        QtCore.QObject.connect(self.connectToStbButton, QtCore.SIGNAL(_fromUtf8("clicked()")), self.labelHddTest.setFocus)
        QtCore.QObject.connect(self.disconnectButton, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.labelHddTest.update)
        QtCore.QMetaObject.connectSlotsByName(SkedYes)

    def retranslateUi(self, SkedYes):
        SkedYes.setWindowTitle(_translate("SkedYes", "SKED YES V0.1", None))
        SkedYes.setWhatsThis(_translate("SkedYes", "Tuner Test", None))
        self.header.setText(_translate("SkedYes", "SKED YES ", None))
        self.telnetConnection.setText(_translate("SkedYes", "Telnet Connection Status:", None))
        self.stbSwVer.setText(_translate("SkedYes", "STB SW Version:", None))
        self.stbEth0Mac.setText(_translate("SkedYes", "ETH0 MAC", None))
        self.stbWiFiMac.setText(_translate("SkedYes", "WiFi MAC", None))
        self.modelInfo.setText(_translate("SkedYes", "Model:", None))
        self.hddSn.setText(_translate("SkedYes", "HDD SN:", None))
        self.connectToStbButton.setText(_translate("SkedYes", "Connect", None))
        self.exitButton.setText(_translate("SkedYes", "Exit", None))
        self.labelHddTest.setText(_translate("SkedYes", "HDD Test", None))
        self.labelUsbTest.setText(_translate("SkedYes", "USB Test", None))
        self.labelSmartcardTest.setText(_translate("SkedYes", "Smartcard ", None))
        self.hddResult.setText(_translate("SkedYes", "PASS", None))
        self.usbResult.setText(_translate("SkedYes", "PASS", None))
        self.smartcardResult.setText(_translate("SkedYes", "PASS", None))
        self.disconnectButton.setText(_translate("SkedYes", "Disconnect", None))
        self.labelTemperature.setText(_translate("SkedYes", "Temperature :", None))
        self.labelTemperatureValue.setText(_translate("SkedYes", "30 C", None))
        self.hddStartButton.setText(_translate("SkedYes", "Start", None))
        self.usbStartButton.setText(_translate("SkedYes", "Start", None))
        self.smartcardStartButton.setText(_translate("SkedYes", "Start", None))
        self.usbStopButton.setText(_translate("SkedYes", "Stop", None))
        self.smartcardStopButton.setText(_translate("SkedYes", "Stop", None))
        self.hddStopButton.setText(_translate("SkedYes", "Stop", None))
        self.autoTestButton.setText(_translate("SkedYes", "Auto Test", None))
        self.fanStopButton.setText(_translate("SkedYes", "Stop", None))
        self.fanStartButton.setText(_translate("SkedYes", "Start", None))
        self.fanResult.setText(_translate("SkedYes", "PASS", None))
        self.labelFanTest.setText(_translate("SkedYes", "Fan Test", None))
        self.fpStartButton.setText(_translate("SkedYes", "Start", None))
        self.labelFpTest.setText(_translate("SkedYes", "VFD Test", None))
        self.fpResult.setText(_translate("SkedYes", "PASS", None))
        self.fpStopButton.setText(_translate("SkedYes", "Stop", None))
        self.labelLedTest.setText(_translate("SkedYes", "Led Test", None))
        self.ledResult.setText(_translate("SkedYes", "PASS", None))
        self.ledStopButton.setText(_translate("SkedYes", "Stop", None))
        self.ledStartButton.setText(_translate("SkedYes", "Start", None))
        self.handleHDCPLabel.setText(_translate("SkedYes", "Program HDCP", None))
        self.handleAppSwUpdate.setText(_translate("SkedYes", "Update UI", None))
        self.hdcpStartButton.setText(_translate("SkedYes", "Start", None))
        self.uiUpdateStartButton.setText(_translate("SkedYes", "Start", None))
        self.statusLabel.setText(_translate("SkedYes", "Status :", None))
        self.fanSpeed.setText(_translate("SkedYes", "FAN: Speed 00000", None))
        self.irStartButton.setText(_translate("SkedYes", "Start", None))
        self.labelIrTest.setText(_translate("SkedYes", "IR Test", None))
        self.irStopButton.setText(_translate("SkedYes", "Stop", None))
        self.irResult.setText(_translate("SkedYes", "PASS", None))
        self.buttonStartButton.setText(_translate("SkedYes", "Start", None))
        self.labelButtonTest.setText(_translate("SkedYes", "Button Test", None))
        self.buttonStopButton.setText(_translate("SkedYes", "Stop", None))
        self.buttonResult.setText(_translate("SkedYes", "PASS", None))
        self.irKeysRecivce.setText(_translate("SkedYes", "Key:", None))
        self.buttonKeysRecivce.setText(_translate("SkedYes", "Key:", None))
        self.labelMacAddressInput.setText(_translate("SkedYes", "MAC Addr", None))
        self.uiUpgradeResult.setText(_translate("SkedYes", "PASS", None))
        self.hdcpKeyResult.setText(_translate("SkedYes", "PASS", None))
        self.tunerStopButton.setText(_translate("SkedYes", "Stop", None))
        self.tunerStartButton.setText(_translate("SkedYes", "Start", None))
        self.labelTunerTest.setText(_translate("SkedYes", "Tuner Test 1", None))
        self.tunerResult.setText(_translate("SkedYes", "PASS", None))
        self.lnbStopButton.setText(_translate("SkedYes", "Stop", None))
        self.labelLnbTest.setText(_translate("SkedYes", "Lnb Test", None))
        self.lnbValue.setText(_translate("SkedYes", "V:18 22Khz: ON", None))
        self.lnbResult.setText(_translate("SkedYes", "PASS", None))
        self.lnbStartButton.setText(_translate("SkedYes", "Start", None))
        self.tunerLnbValue.setText(_translate("SkedYes", "V:13 22Khz: OFF", None))

